"""
create-conf.py
--------------
Generate a stoichiometric FCC TiN supercell and write a LAMMPS .data file
suitable for MEAM potentials.
 
The atom-type labels (Ti, N) are written in the Masses section header
so LAMMPS and post-processing tools can identify them unambiguously.
 
Usage
-----
    python3 create-conf.py <N>
 
    N  – number of unit-cell repeats along x, y, and z (same for all axes)
 
Examples
--------
    python3 create-conf.py 3   →  3x3x3 supercell (216 atoms) → TiN_3x3x3.data
    python3 create-conf.py 5   →  5x5x5 supercell (1000 atoms) → TiN_5x5x5.data
 
Dependencies
------------
    pip install ase numpy
"""
 
import sys
import numpy as np
from ase import Atoms
 
# ---------------------------------------------------------------------------
# Parse CLI argument
# ---------------------------------------------------------------------------
if len(sys.argv) < 2:
    print("Usage: python3 create-conf.py <N_REPEATS>")
    print("  e.g. python3 create-conf.py 3   →  3x3x3 supercell")
    sys.exit(1)
 
N = int(sys.argv[1])
OUTPUT_FILE = f"TiN_{N}x{N}x{N}.data"
 
# ---------------------------------------------------------------------------
# Crystal parameters
# ---------------------------------------------------------------------------
# TiN rock-salt (B1) structure, space group Fm-3m.
# Experimental lattice parameter: 4.242 Å.
# Adjust to match your MEAM potential's equilibrium value if needed.
A_LATTICE = 4.242   # Å
 
# Atom-type mapping  (must match pair_coeff element order in LAMMPS)
ATOM_TYPES = {
    "Ti": 1,
    "N":  2,
}
 
# Atomic masses (g/mol)
MASSES = {
    "Ti": 47.867,
    "N":  14.007,
}
 
# ---------------------------------------------------------------------------
# Build conventional cubic unit cell  (4 Ti + 4 N = 8 atoms)
# ---------------------------------------------------------------------------
a = A_LATTICE
 
ti_frac = [
    [0.0, 0.0, 0.0],
    [0.5, 0.5, 0.0],
    [0.5, 0.0, 0.5],
    [0.0, 0.5, 0.5],
]
n_frac = [
    [0.5, 0.5, 0.5],
    [0.0, 0.0, 0.5],
    [0.0, 0.5, 0.0],
    [0.5, 0.0, 0.0],
]
 
symbols   = ["Ti"] * 4 + ["N"] * 4
all_frac  = ti_frac + n_frac
cell      = np.diag([a, a, a])
 
unit_cell = Atoms(
    symbols=symbols,
    scaled_positions=all_frac,
    cell=cell,
    pbc=True,
)
 
# ---------------------------------------------------------------------------
# Replicate to supercell
# ---------------------------------------------------------------------------
supercell = unit_cell.repeat([N, N, N])
 
positions = supercell.get_positions()
sc_symbols = list(supercell.get_chemical_symbols())
Lx, Ly, Lz = supercell.cell[0, 0], supercell.cell[1, 1], supercell.cell[2, 2]
 
n_Ti  = sc_symbols.count("Ti")
n_N   = sc_symbols.count("N")
n_tot = len(supercell)
 
print(f"Supercell : {N}x{N}x{N}")
print(f"  Ti atoms : {n_Ti}")
print(f"  N  atoms : {n_N}")
print(f"  Total    : {n_tot}  (Ti:N = 1:1)")
print(f"  Box      : {Lx:.4f} x {Ly:.4f} x {Lz:.4f}  Å")
 
# ---------------------------------------------------------------------------
# Write LAMMPS .data file manually
# ---------------------------------------------------------------------------
with open(OUTPUT_FILE, "w") as f:
 
    # --- Header comment (first line) ---
    f.write(f"TiN rock-salt FCC supercell {N}x{N}x{N} — generated by create-conf.py\n\n")
 
    # --- Counts ---
    f.write(f"{n_tot} atoms\n")
    f.write(f"{len(ATOM_TYPES)} atom types\n\n")
 
    # --- Box bounds ---
    f.write(f"0.0 {Lx:.6f} xlo xhi\n")
    f.write(f"0.0 {Ly:.6f} ylo yhi\n")
    f.write(f"0.0 {Lz:.6f} zlo zhi\n\n")
 
    # --- Masses  (element symbol written as inline comment) ---
    f.write("Masses\n\n")
    for element, type_id in sorted(ATOM_TYPES.items(), key=lambda x: x[1]):
        f.write(f"  {type_id}  {MASSES[element]:.4f}  # {element}\n")
    f.write("\n")
 
    # --- Atoms  (atom_style atomic: id  type  x  y  z) ---
    f.write("Atoms  # atomic\n\n")
    for atom_id, (sym, pos) in enumerate(zip(sc_symbols, positions), start=1):
        t = ATOM_TYPES[sym]
        x, y, z = pos
        f.write(f"  {atom_id:>8d}  {t}  {x:>14.8f}  {y:>14.8f}  {z:>14.8f}  # {sym}\n")
 
print(f"\nLAMMPS data file written to: {OUTPUT_FILE}")
print("\n--- Suggested LAMMPS input snippet ---")
print(f"read_data    {OUTPUT_FILE}")
print("pair_style   meam")
print("pair_coeff   * * library.meam Ti N TiN.meam Ti N")
print("# type 1 = Ti  |  type 2 = N")
 